Make more good

diff --git a/build b/build
--- a/build
+++ b/build
@@ -13,49 +13,48 @@ bdir4=/media/shagbag913/Roms/roms/aicp
 ### FUNCTIONS ###
 autopilot() {
 ## AEX ##
-#   cd $bdir1
- #  sync
-  # lunchh
-#   lunch aosp_sailfish-userdebug
- #  echo "**Building AospExtended**" | python3 ~/localscripts/dis.py
-  # make aex -j6
-#      if [ "$?" = "0" ]; then
- #        echo "*AospExtended Built Successfully!*" | python3 ~/localscripts/dis.py
-  #    else
-   #      echo "*AospExtended Failed...*" | python3 ~/localscripts/dis.py
-    #  fi
-#   curl -T /media/shagbag913/Roms/roms/aex/out/target/product/sailfish/AospExtended-v5*.zip ftp://shagbag913:$pas@uploads.androidfilehost.com
+   cd $bdir1
+   sync
+   lunchh
+   lunch aosp_sailfish-userdebug
+   echo "**Building AospExtended**" | python3 ~/localscripts/dis.py
+   make aex -j6
+      if [ "$?" = "0" ]; then
+         echo "*AospExtended Built Successfully!*" | python3 ~/localscripts/dis.py
+      else
+         echo "*AospExtended Failed...*" | python3 ~/localscripts/dis.py
+      fi
+   curl -T /media/shagbag913/Roms/roms/aex/out/target/product/sailfish/AospExtended-v5*.zip ftp://shagbag913:$pas@uploads.androidfilehost.com
 ## DU ##
-#   cd $bdir2
- #  sync
-  # echo "**Building Dirty Unicorns**" | python3 ~/localscripts/dis.py
-#   brunchh
- #     if [ "$?" = "0" ]; then
-  #       echo "*Dirty Unicorns Built Successfully!*" | python3 ~/localscripts/dis.py
-   #   else
-    #     echo "*Dirty Unicorns Build Failed...*" | python3 ~/localscripts/dis.py
-#      fi
- #  curl -T /media/shagbag913/Roms/roms/du/out/target/product/sailfish/du_sailfish-v*.zip ftp://shagbag913:$pas@uploads.androidfilehost.com
+   cd $bdir2
+   sync
+   echo "**Building Dirty Unicorns**" | python3 ~/localscripts/dis.py
+   brunchh
+      if [ "$?" = "0" ]; then
+         echo "*Dirty Unicorns Built Successfully!*" | python3 ~/localscripts/dis.py
+      else
+         echo "*Dirty Unicorns Build Failed...*" | python3 ~/localscripts/dis.py
+      fi
+   curl -T /media/shagbag913/Roms/roms/du/out/target/product/sailfish/du_sailfish-v*.zip ftp://shagbag913:$pas@uploads.androidfilehost.com
 ## DOT ##
-#   cd $bdir3
- #  sync
-  # echo Copying theming patch
-#   rm -rf /media/shagbag913/Roms/roms/dot/build/core/build_rro_package.mk
- #  cp /media/shagbag913/Roms/patches/build_rro_package.mk /media/shagbag913/Roms/roms/dot/build/core/build_rro_package.mk
-#   echo "**Building dotOS**" | python3 ~/localscripts/dis.py
- #  brunchh
-  #    if [ "$?" = "0" ]; then
-   #      echo "*dotOS Built Successfully!*" | python3 ~/localscripts/dis.py
-    #  else
-#         echo "*dotOS Build Failed...*" | python3 ~/localscripts/dis.py
- #     fi
-  # curl -T /media/shagbag913/Roms/roms/dot/out/target/product/sailfish/dotOS-O-*.zip ftp://shagbag913:$pas@uploads.androidfilehost.com
+   cd $bdir3
+   sync
+   echo Copying theming patch
+   rm -rf /media/shagbag913/Roms/roms/dot/build/core/build_rro_package.mk
+   cp /media/shagbag913/Roms/patches/build_rro_package.mk /media/shagbag913/Roms/roms/dot/build/core/build_rro_package.mk
+   echo "**Building dotOS**" | python3 ~/localscripts/dis.py
+   brunchh
+      if [ "$?" = "0" ]; then
+         echo "*dotOS Built Successfully!*" | python3 ~/localscripts/dis.py
+      else
+         echo "*dotOS Build Failed...*" | python3 ~/localscripts/dis.py
+      fi
+   curl -T /media/shagbag913/Roms/roms/dot/out/target/product/sailfish/dotOS-O-*.zip ftp://shagbag913:$pas@uploads.androidfilehost.com
 ## AICP ##
    cd $bdir4
    sync
    echo "**Building AICP**" | python3 ~/localscripts/dis.py
-   . build/envsetup.sh
-   brunch sailfish
+   brunchh
       if [ "$?" = "0" ]; then
          echo "*AICP Built Successfully!*" | python3 ~/localscripts/dis.py
       else
@@ -104,7 +103,7 @@ brunchh() {
    time (echo Setting up build enviroment...
    . build/envsetup.sh
    echo Building...
-   brunch sailfish -j6)
+   brunch sailfish)
    if [ "$?" = "0" ]; then
      echo Build Successful!
    else
