all: indention 4 spaced -> 2 spaces
It looks better && its what Google does
thanks sed

Signed-off-by: shagbag913 <sh4gbag913@gmail.com>

diff --git a/build-arch b/build-arch
--- a/build-arch
+++ b/build-arch
@@ -2,33 +2,33 @@
 
 # source common, download if it does not exist
 if ! source common &>/dev/null; then
-    echo -e "\e[0;34m---------------------------------------------"
-    echo -e "INFO:'common' script not found, downloading.."
-    echo -e "---------------------------------------------\e[0m"
-    wget https://github.com/shagbag913/scripts/raw/master/common &>/dev/null
-    source common
+  echo -e "\e[0;34m---------------------------------------------"
+  echo -e "INFO:'common' script not found, downloading.."
+  echo -e "---------------------------------------------\e[0m"
+  wget https://github.com/shagbag913/scripts/raw/master/common &>/dev/null
+  source common
 fi
 
 # Detect installed AUR helper
 for a in trizen pakku yaourt aurman; do
-    if command -v "${a}" &>/dev/null; then
-         AUR_HELPER="${a}" && break
-    fi
+  if command -v "${a}" &>/dev/null; then
+     AUR_HELPER="${a}" && break
+  fi
 done
 
 if ! command -v git &>/dev/null; then
-    info "Installing 'git'"
-    sudo pacman -S --noconfirm git
+  info "Installing 'git'"
+  sudo pacman -S --noconfirm git
 fi
 
 # Install pakku if no AUR helper was found
 if [[ -z "${AUR_HELPER}" ]]; then
-    info "No AUR helper was found. Installing pakku.."
-    sleep 1
-    cd "${TMPDIR:-/tmp}" || exit
-    git clone https://aur.archlinux.org/pakku.git
-    cd pakku && makepkg -si --noconfirm
-    AUR_HELPER=pakku
+  info "No AUR helper was found. Installing pakku.."
+  sleep 1
+  cd "${TMPDIR:-/tmp}" || exit
+  git clone https://aur.archlinux.org/pakku.git
+  cd pakku && makepkg -si --noconfirm
+  AUR_HELPER=pakku
 fi
 
 # Install the needed packages to build
@@ -44,11 +44,11 @@ cd "${HOME}"/bin || exit
 # Add stuff to ~/.bashrc if it is not already there
 src=0
 for e in "export LC_ALL=C" 'PATH="${HOME}/bin:${PATH}"'; do
-    if ! cat "${HOME}"/.bashrc | grep "$e" &>/dev/null; then
-        echo "$e" >> "${HOME}"/.bashrc
-        src=$(("${src}"+1))
-        if [[ "${src}" = 1 ]]; then
-            info "Type 'source ~/.bashrc' to complete set up!"
-        fi
+  if ! cat "${HOME}"/.bashrc | grep "$e" &>/dev/null; then
+    echo "$e" >> "${HOME}"/.bashrc
+    src=$(("${src}"+1))
+    if [[ "${src}" = 1 ]]; then
+      info "Type 'source ~/.bashrc' to complete set up!"
     fi
+  fi
 done
diff --git a/buildkernel b/buildkernel
--- a/buildkernel
+++ b/buildkernel
@@ -6,43 +6,43 @@ GCC_DIR="/media/shagbag913/Roms/kernel/toolchains/build-tools-gcc/aarch64-linux-
 export ARCH=arm64
 
 while [[ "${#}" -ge 1 ]]; do
-    case "${1}" in
-        "-d") DIRTY=true;;
-        "-g") GCC=true;;
-        "-c") CLANG=true;;
-    esac
-    shift
+  case "${1}" in
+    "-d") DIRTY=true;;
+    "-g") GCC=true;;
+    "-c") CLANG=true;;
+  esac
+  shift
 done
 
 if [[ -z "${DIRTY}" ]]; then
-    make clean
-    make mrproper
+  make clean
+  make mrproper
 fi
 
 make shag_defconfig
 
 if [[ -n "${CLANG}" ]]; then
-    info "Building with Clang"
-    make "${PAR_THREAD}" \
-        CC="ccache /media/shagbag913/Roms/kernel/toolchains/linux-x86/clang-r328903/bin/clang" \
-        CLANG_TRIPLE=aarch64-linux-gnu- \
-        CROSS_COMPILE="${GCC_DIR}" && SUCCESS=true
+  info "Building with Clang"
+  make "${PAR_THREAD}" \
+    CC="ccache /media/shagbag913/Roms/kernel/toolchains/linux-x86/clang-r328903/bin/clang" \
+    CLANG_TRIPLE=aarch64-linux-gnu- \
+    CROSS_COMPILE="${GCC_DIR}" && SUCCESS=true
 fi
 
 if [[ -n "${GCC}" ]]; then
-    info "Building with GCC"
-    make "${PAR_THREAD}" \
-        CROSS_COMPILE="ccache ${GCC_DIR}" && SUCCESS=true
+  info "Building with GCC"
+  make "${PAR_THREAD}" \
+    CROSS_COMPILE="ccache ${GCC_DIR}" && SUCCESS=true
 fi
 
 if [[ ${SUCCESS} = true ]]; then
-    info "Kernel build successful!"
-    cd /media/shagbag913/Roms/kernel/shagkernel/ak2 || { error "Couldn't find AnyKernel2 folder!"; exit 1; }
-    cp /media/shagbag913/Roms/kernel/shagkernel/arch/arm64/boot/Image.lz4-dtb .
-    ./zip.sh
-    cd /media/shagbag913/Roms/gdrive || { warn "Couldn't find GDrive folder! Not uploading to gdrive.."; exit 1; }
-    rm -rf Kernel/*
-    cp /media/shagbag913/Roms/kernel/shagkernel/ak2/ShagKernel*.zip ./Kernel
-    grive
-    info "Kernel uploaded to GDrive"
+  info "Kernel build successful!"
+  cd /media/shagbag913/Roms/kernel/shagkernel/ak2 || { error "Couldn't find AnyKernel2 folder!"; exit 1; }
+  cp /media/shagbag913/Roms/kernel/shagkernel/arch/arm64/boot/Image.lz4-dtb .
+  ./zip.sh
+  cd /media/shagbag913/Roms/gdrive || { warn "Couldn't find GDrive folder! Not uploading to gdrive.."; exit 1; }
+  rm -rf Kernel/*
+  cp /media/shagbag913/Roms/kernel/shagkernel/ak2/ShagKernel*.zip ./Kernel
+  grive
+  info "Kernel uploaded to GDrive"
 fi
diff --git a/buildrom b/buildrom
--- a/buildrom
+++ b/buildrom
@@ -26,91 +26,91 @@ out="out/target/product/${DEVICE}"
 
 # Functions
 sync() {
-    info "Syncing Up."
-    if repo sync ${PAR_THREAD} --no-tags --no-clone-bundle --force-sync -f -q; then
-        info "Sync Successful!"
-    else
-        error "Sync Failed!" && exit 1
-    fi
+  info "Syncing Up."
+  if repo sync ${PAR_THREAD} --no-tags --no-clone-bundle --force-sync -f -q; then
+    info "Sync Successful!"
+  else
+    error "Sync Failed!" && exit 1
+  fi
 }
 clean() {
-    info "Makin Clobber."
-    cd $romdir1
-    make clobber
-    cd $romdir2
-    make clobber
-    if [[ ${DC} = true ]]; then dc_msg "Outputs Cleaned. These builds will take a while :grin:"; fi
+  info "Makin Clobber."
+  cd $romdir1
+  make clobber
+  cd $romdir2
+  make clobber
+  if [[ ${DC} = true ]]; then dc_msg "Outputs Cleaned. These builds will take a while :grin:"; fi
 }
 brinch() {
-    info "Brunching."
-    . build/envsetup.sh
-    brunch ${DEVICE}
+  info "Brunching."
+  . build/envsetup.sh
+  brunch ${DEVICE}
 }
 gdrive() {
-    if [[ ${GDRIVE} = true ]]; then
-        if [[ $test != true ]]; then
-            cp `ls -rt ${romdir1}/${out}/${romzip1}*.zip  | tail -1` ${gdir1}
-            cp `ls -rt ${romdir2}/${out}/${romzip2}*.zip  | tail -1` ${gdir2}
-	    cd ${GD_FOLDER} && grive
-            dc_msg "**Google Drive: Builds uploaded. ${GD_URL}**"
-        else
-            cp `ls -rt ${romdir1}/${out}/${romzip1}*.zip  | tail -1` ${gdirtest}
-            cp `ls -rt ${romdir2}/${out}/${romzip2}*.zip  | tail -1` ${gdirtest}
-            cd ${GD_FOLDER} && grive
-            dc_msg "**Google Drive: Test builds uploaded.** *Flash these at your own risk!* ${GD_TESTURL}"
-        fi
+  if [[ ${GDRIVE} = true ]]; then
+    if [[ $test != true ]]; then
+      cp `ls -rt ${romdir1}/${out}/${romzip1}*.zip  | tail -1` ${gdir1}
+      cp `ls -rt ${romdir2}/${out}/${romzip2}*.zip  | tail -1` ${gdir2}
+	  cd ${GD_FOLDER} && grive
+      dc_msg "**Google Drive: Builds uploaded. ${GD_URL}**"
+    else
+      cp `ls -rt ${romdir1}/${out}/${romzip1}*.zip  | tail -1` ${gdirtest}
+      cp `ls -rt ${romdir2}/${out}/${romzip2}*.zip  | tail -1` ${gdirtest}
+      cd ${GD_FOLDER} && grive
+      dc_msg "**Google Drive: Test builds uploaded.** *Flash these at your own risk!* ${GD_TESTURL}"
     fi
+  fi
 }
 gdrivepurge() {
-    info "Cleaning GDrive Directories."
-    for n in ${gdir1} ${gdir2}; do
-        rm -rf $n/*
-    done
-    cd ${GD_FOLDER} 
-    grive
-    info "GDrive folders purged."
-    if [[ ${DC} = true ]]; then dc_msg "**Google Drive: ROM's purged.**"; fi
+  info "Cleaning GDrive Directories."
+  for n in ${gdir1} ${gdir2}; do
+    rm -rf $n/*
+  done
+  cd ${GD_FOLDER} 
+  grive
+  info "GDrive folders purged."
+  if [[ ${DC} = true ]]; then dc_msg "**Google Drive: ROM's purged.**"; fi
 }
 gdrivepurgetest() {
-    info "Cleaning GDrive Directories."
-    rm -rf ${gdirtest}/*
-    cd ${GD_FOLDER}
-    grive
-    info "GDrive folders purged."
-    if [[ ${DC} = true ]]; then dc_msg "**Google Drive: test builds purged.**"; fi
+  info "Cleaning GDrive Directories."
+  rm -rf ${gdirtest}/*
+  cd ${GD_FOLDER}
+  grive
+  info "GDrive folders purged."
+  if [[ ${DC} = true ]]; then dc_msg "**Google Drive: test builds purged.**"; fi
 }
 autopilot() {
-    cd $romdir1
-    sync
-    if [[ ${DC} = true ]]; then dc_msg "**Building ${name1}.**"; fi
-    DATE_START1=$(date +"%s")
-    . build/envsetup.sh
-    lunch aosp_sailfish-userdebug
-    make aex ${PAR_THREAD} && rom1=successful
-    DATE_END1=$(date +"%s")
-    DIFF1=$(($DATE_END1 - $DATE_START1))
-        if [[ ${DC} = true ]]; then
-            if [[ $rom1 = successful ]]; then
-                dc_msg "*Build Successful in $(($DIFF1 / 60)) minute(s).*"
-            else 
-                dc_msg "*Build Failed in $(($DIFF1 / 60)) minute(s).*"
-            fi
-        fi
-    cd $romdir2
-    sync
-    if [[ ${DC} = true ]]; then dc_msg "**Building ${name2}.**"; fi
-    DATE_START2=$(date +"%s")
-    brinch && rom2=successful
-    DATE_END2=$(date +"%s")
-    DIFF2=$(($DATE_END2 - $DATE_START2))
-        if [[ ${DC} = true ]]; then
-            if [[ $rom2 = successful ]]; then
-                dc_msg "*Build Succesful in $(($DIFF2 / 60)) minute(s).*"
-            else
-                dc_msg "*Build Failed in $(($DIFF2 / 60)) minute(s).*"
-            fi
-        fi
-    gdrive
+  cd $romdir1
+  sync
+  if [[ ${DC} = true ]]; then dc_msg "**Building ${name1}.**"; fi
+  DATE_START1=$(date +"%s")
+  . build/envsetup.sh
+  lunch aosp_sailfish-userdebug
+  make aex ${PAR_THREAD} && rom1=successful
+  DATE_END1=$(date +"%s")
+  DIFF1=$(($DATE_END1 - $DATE_START1))
+    if [[ ${DC} = true ]]; then
+      if [[ $rom1 = successful ]]; then
+        dc_msg "*Build Successful in $(($DIFF1 / 60)) minute(s).*"
+      else 
+        dc_msg "*Build Failed in $(($DIFF1 / 60)) minute(s).*"
+      fi
+    fi
+  cd $romdir2
+  sync
+  if [[ ${DC} = true ]]; then dc_msg "**Building ${name2}.**"; fi
+  DATE_START2=$(date +"%s")
+  brinch && rom2=successful
+  DATE_END2=$(date +"%s")
+  DIFF2=$(($DATE_END2 - $DATE_START2))
+    if [[ ${DC} = true ]]; then
+      if [[ $rom2 = successful ]]; then
+        dc_msg "*Build Succesful in $(($DIFF2 / 60)) minute(s).*"
+      else
+        dc_msg "*Build Failed in $(($DIFF2 / 60)) minute(s).*"
+      fi
+    fi
+  gdrive
 }
 
 # Checks
@@ -118,14 +118,14 @@ grive_chk
 dc_chk
 
 while [ "$#" -ge 1 ]; do
-    case $1 in
-        -s | --sync ) sync;;
-        -c | --clean ) clean;;
-        -a | --autopilot ) autopilot;;
-        -p | --gdrivepurge ) gdrivepurge;;
-        -tp | --gdrivetestpurge ) gdrivepurgetest;;
-        -t | --test ) test=true;;
-        * ) error "buildrom ${1} is not a supported command :/";;
-    esac
+  case $1 in
+    -s | --sync ) sync;;
+    -c | --clean ) clean;;
+    -a | --autopilot ) autopilot;;
+    -p | --gdrivepurge ) gdrivepurge;;
+    -tp | --gdrivetestpurge ) gdrivepurgetest;;
+    -t | --test ) test=true;;
+    * ) error "buildrom ${1} is not a supported command :/";;
+  esac
 shift
 done
diff --git a/getimages b/getimages
--- a/getimages
+++ b/getimages
@@ -14,7 +14,7 @@ FI_SAVE_DIR=${FI_DOWNLOAD_DIR}/"${BUILD_NUM}"
 
 cd ${FI_DOWNLOAD_DIR} || return
 if [[ ! -e ${FI_ZIP} ]]; then
-    if ! wget "${URL}"; then { error "Download failed! Exiting..."; exit 1; }; fi
+  if ! wget "${URL}"; then { error "Download failed! Exiting..."; exit 1; }; fi
 fi
 
 unzip "${FI_ZIP}"
@@ -27,14 +27,14 @@ cp boot.img "${FI_SAVE_DIR}/"
 # TRANSFER IMAGES TO GOOGLE DRIVE
 grive_chk
 if [[ ${GDRIVE} = true ]]; then
-    GD_IMAGESURL=http://gg.gg/shagbag913_images
-    cp -r "${FI_SAVE_DIR}" "${GD_FOLDER}"/Images
-    cd "${GD_FOLDER}" || return
-    grive
-    dc_chk
-    if [[ ${DC} = true ]]; then
-        dc_msg "**Google Drive: ${BUILD_NUM} vendor and boot images uploaded! ${GD_IMAGESURL}**"
-    fi
+  GD_IMAGESURL=http://gg.gg/shagbag913_images
+  cp -r "${FI_SAVE_DIR}" "${GD_FOLDER}"/Images
+  cd "${GD_FOLDER}" || return
+  grive
+  dc_chk
+  if [[ ${DC} = true ]]; then
+    dc_msg "**Google Drive: ${BUILD_NUM} vendor and boot images uploaded! ${GD_IMAGESURL}**"
+  fi
 fi
 
 # REMOVE FACTORY IMAGE ZIP
diff --git a/merge-ls b/merge-ls
--- a/merge-ls
+++ b/merge-ls
@@ -5,7 +5,7 @@ if [[ ! -e Makefile ]]; then { error "Not in a kernel directory! Exiting..."; ex
 
 # Fetch/add stable remote if it does not exist
 if git remote add linux-stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/ &>/dev/null; then
-    info "Added remote 'linux-stable'"
+  info "Added remote 'linux-stable'"
 fi
 
 info "Fetching latest stable kernel tree"
@@ -20,10 +20,10 @@ LATEST_VER=$(git tag --sort=-taggerdate -l v"${MAJOR_VER}"* | head -n 1)
 
 # Exit the script if the kernel version is already the latest
 if [[ v${VER} = "${LATEST_VER}" ]]; then
-    info "Kernel already up to date! :)" && exit 1
+  info "Kernel already up to date! :)" && exit 1
 fi
 
 # Merge!
 if ! git merge "${LATEST_VER}"; then
-    error "Merge failed! Fix the conflicts!"
+  error "Merge failed! Fix the conflicts!"
 fi
