all: cleanup && add exit to error()
it makes sense to add `exit 1` to function error,
because everytime I use error() I add exit to the
end

Signed-off-by: shagbag913 <sh4gbag913@gmail.com>

diff --git a/buildkernel b/buildkernel
--- a/buildkernel
+++ b/buildkernel
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 source common
 
-if [[ ! -e Makefile ]]; then { error "Not in a kernel directory! Exiting..."; exit 1; }; fi
+if [[ ! -e Makefile ]]; then error "Not in a kernel directory! Exiting..."; fi
 GCC_DIR="/media/shagbag913/Roms/kernel/toolchains/build-tools-gcc/aarch64-linux-gnu/bin/aarch64-linux-gnu-"
 export ARCH=arm64
 
@@ -37,10 +37,10 @@ fi
 
 if [[ ${SUCCESS} = true ]]; then
   info "Kernel build successful!"
-  cd /media/shagbag913/Roms/kernel/shagkernel/ak2 || { error "Couldn't find AnyKernel2 folder!"; exit 1; }
+  cd /media/shagbag913/Roms/kernel/shagkernel/ak2 || error "Couldn't find AnyKernel2 folder!"
   cp /media/shagbag913/Roms/kernel/shagkernel/arch/arm64/boot/Image.lz4-dtb .
   ./zip.sh
-  cd /media/shagbag913/Roms/gdrive || { warn "Couldn't find GDrive folder! Not uploading to gdrive.."; exit 1; }
+  cd /media/shagbag913/Roms/gdrive || error "Couldn't find GDrive folder! Not uploading to gdrive.."
   rm -rf Kernel/*
   cp /media/shagbag913/Roms/kernel/shagkernel/ak2/ShagKernel*.zip ./Kernel
   grive
diff --git a/getimages b/getimages
--- a/getimages
+++ b/getimages
@@ -8,13 +8,13 @@ FI_FOLDER="$(echo "${FI_ZIP}" | awk -F-factory '{print $1}')"
 BUILD_NUM="$(echo "${FI_ZIP}" | sed -n 's/-factory.*//; s/.*sailfish-//p')"
 FI_SAVE_DIR=${FI_DOWNLOAD_DIR}/"${BUILD_NUM}"
 
-[[ -z ${FI_SAVE_DIR} ]] && { error "Save location not set! Exiting..."; exit 1; }
-[[ ! -e ${FI_DOWNLOAD_DIR} ]] && { error "${RED}Save location ${FI_SAVE_DIR} does not exist! Exiting..."; exit 1; }
-[[ -z ${URL} ]] && { error "No URL specified! Exiting..."; exit 1; }
+[[ -z ${FI_SAVE_DIR} ]] && error "Save location not set! Exiting..."
+[[ ! -e ${FI_DOWNLOAD_DIR} ]] && error "${RED}Save location ${FI_SAVE_DIR} does not exist! Exiting..."
+[[ -z ${URL} ]] && error "No URL specified! Exiting..."
 
 cd ${FI_DOWNLOAD_DIR} || return
 if [[ ! -e ${FI_ZIP} ]]; then
-  if ! wget "${URL}"; then { error "Download failed! Exiting..."; exit 1; }; fi
+  if ! wget "${URL}"; then error "Download failed! Exiting..."; fi
 fi
 
 unzip "${FI_ZIP}"
