buildid/buildkernel/getimages/merge-ls: cleanup && fix shellcheck errors
Signed-off-by: shagbag913 <sh4gbag913@gmail.com>

diff --git a/buildkernel b/buildkernel
--- a/buildkernel
+++ b/buildkernel
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 source common
 
-if [[ ! -e Makefile ]]; then error "Not in a kernel directory! Exiting..."; exit 1; fi
+if [[ ! -e Makefile ]]; then { error "Not in a kernel directory! Exiting..."; exit 1; }; fi
 
 GCC_DIR="/media/shagbag913/Roms/kernel/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-"
 IMAGE_DIR="/media/shagbag913/Roms/kernel/shagkernel/arch/arm64/boot"
@@ -14,7 +14,7 @@ make shag_defconfig
 
 if [[ ${1} = "-c" ]]; then
     info "Building with Clang"
-    make ${PAR_THREAD} \
+    make "${PAR_THREAD}" \
         CC="ccache /media/shagbag913/Roms/kernel/toolchains/linux-x86/clang-r328903/bin/clang" \
         CLANG_TRIPLE=aarch64-linux-gnu- \
         CROSS_COMPILE="${GCC_DIR}" && SUCCESS=true
@@ -22,17 +22,17 @@ fi
 
 if [[ ${1} = "-g" ]]; then
     info "Building with GCC"
-    make ${PAR_THREAD} \
+    make "${PAR_THREAD}" \
         CROSS_COMPILE="ccache ${GCC_DIR}" && SUCCESS=true
 fi
 
 if [[ ${SUCCESS} = true ]]; then
     info "Kernel build successful!"
-    cd /media/shagbag913/Roms/kernel/shagkernel/ak2
+    cd /media/shagbag913/Roms/kernel/shagkernel/ak2 || { error "Couldn't find AnyKernel2 folder!"; exit 1; }
     cp ${IMAGE_DIR}/Image.lz4 kernel/
     cp ${IMAGE_DIR}/dts/htc/*.dtb dtbs/
     ./zip.sh
-    cd /media/shagbag913/Roms/gdrive
+    cd /media/shagbag913/Roms/gdrive || { warn "Couldn't find GDrive folder! Not uploading to gdrive.."; exit 1; }
     rm -rf Kernel/*
     cp /media/shagbag913/Roms/kernel/shagkernel/ak2/ShagKernel*.zip ./Kernel
     grive
diff --git a/getimages b/getimages
--- a/getimages
+++ b/getimages
@@ -8,21 +8,19 @@ FI_FOLDER="$(echo "${FI_ZIP}" | awk -F-factory '{print $1}')"
 BUILD_NUM="$(echo "${FI_ZIP}" | sed -n 's/-factory.*//; s/.*sailfish-//p')"
 FI_SAVE_DIR=${FI_DOWNLOAD_DIR}/"${BUILD_NUM}"
 
-[[ -z ${FI_SAVE_DIR} ]] && error "Save location not set! Exiting..." && exit 1
-[[ ! -e ${FI_DOWNLOAD_DIR} ]] && error "${RED}Save location ${FI_SAVE_DIR} does not exist! Exiting..." && exit 1
-[[ -z ${URL} ]] && error "No URL specified! Exiting..." && exit 1
+[[ -z ${FI_SAVE_DIR} ]] && { error "Save location not set! Exiting..."; exit 1; }
+[[ ! -e ${FI_DOWNLOAD_DIR} ]] && { error "${RED}Save location ${FI_SAVE_DIR} does not exist! Exiting..."; exit 1; }
+[[ -z ${URL} ]] && { error "No URL specified! Exiting..."; exit 1; }
 
 cd ${FI_DOWNLOAD_DIR} || return
 if [[ ! -e ${FI_ZIP} ]]; then
-    if ! wget "${URL}"; then
-        error "Download failed! Exiting..." && exit 1
-    fi
+    if ! wget "${URL}"; then { error "Download failed! Exiting..."; exit 1; }; fi
 fi
 
 unzip "${FI_ZIP}"
 cd "${FI_FOLDER}" || return
 unzip "image-${FI_FOLDER}.zip"
-[[ ! -e ${FI_SAVE_DIR} ]] && mkdir "${FI_SAVE_DIR}" && info "Created directory ${FI_SAVE_DIR}"
+[[ ! -e ${FI_SAVE_DIR} ]] && { mkdir "${FI_SAVE_DIR}"; info "Created directory ${FI_SAVE_DIR}"; }
 cp vendor.img "${FI_SAVE_DIR}/"
 cp boot.img "${FI_SAVE_DIR}/"
 
