getimages: completely rewrite
Signed-off-by: shagbag913 <sh4gbag913@gmail.com>

diff --git a/getimages b/getimages
--- a/getimages
+++ b/getimages
@@ -1,46 +1,62 @@
 #!/bin/bash
-set -e
-
-# Source common stuff
+#
+# Source common
 source common
-
-# Upload to gdrive? Leave blank If you don't want to.
-GD_IMAGES="${GD_FOLDER}/Images"
+#
+###############
+## Variables ##
+###############
+#
+# FI_DOWNLOAD_DIR: Directory to download the factory image to
+# FI_SAVE_DIR: Where to save the desired images
+# URL: URL to the direct download link of the factory image
+# FI_ZIP: The name of the factory image ZIP file
+# FI_FOLDER: The extracted factory image
+# IMAGE_ZIP: The zip containing all of the image files
+#
+FI_DOWNLOAD_DIR="/media/shagbag913/Roms/factimages"
+FI_SAVE_DIR="${FI_DOWNLOAD_DIR}/$(date +%b)-images"
+URL="$1"
+FI_ZIP="$(basename "${URL}")"
+FI_FOLDER="$(echo "${FI_ZIP}" | awk -F-factory '{print $1}')"
+IMAGE_ZIP="image-${FI_FOLDER}.zip"
+#
+##################
+# Sanity Checks ##
+##################
+#
+[[ -z ${FI_SAVE_DIR} ]] && echo -e "${RED}Save location not set! Exiting...${RESTORE}" && exit 1
+[[ ! -e ${FI_DOWNLOAD_DIR} ]] && echo -e "${RED}Save location ${FI_SAVE_DIR} does not exist! Exiting...${RESTORE}" && exit 1
+[[ -z ${URL} ]] && echo -e "${RED}No URL specified! Exiting...${RESTORE}" && exit 1
+#
+################################
+## Download the factory image ##
+################################
+#
+cd ${FI_DOWNLOAD_DIR}
+## Only download the zip if it doesn't already exist ##
+if [[ ! -e ${FI_ZIP} ]]; then
+    wget ${URL}
+        if [[ $? -gt 0 ]]; then
+            echo -e "${RED}Download failed! Exiting...${RESTORE}" && exit 1
+        fi
+fi
+unzip ${FI_ZIP}
+cd ${FI_FOLDER}
+unzip ${IMAGE_ZIP}
+## Create the save directory if it does not exist ##
+[[ ! -e ${FI_SAVE_DIR} ]] && mkdir "${FI_SAVE_DIR}" && echo -e "${BLUE}Created directory ${FI_SAVE_DIR}${RESTORE}"
+cp vendor.img ${FI_SAVE_DIR}/${DEVICE}-vendor-$(date +%b).img
+cp boot.img ${FI_SAVE_DIR}/${DEVICE}-boot-$(date +%b).img
+#
+#####################################
+## Transfer images to Google Drive ##
+#####################################
+#
 GD_IMAGESURL=http://gg.gg/shagbag913_images
+cp -r ${FI_SAVE_DIR} ${GD_FOLDER}/Images
+cd ${GD_FOLDER}
+grive_chk && grive && dc_msg "**Google Drive: $(date +%B)s vendor and boot images uploaded! ${GD_IMAGESURL}**"
 
-# dir is where you want the factory image to be downloaded too.
-DIR=/media/shagbag913/Roms/factimages
-
-# savedir is where you want the vendor, bootloader, and radio images to be saved too.
-# if you name it 'images-${folder}', it will be named 'images-<build-id>'.
-SAVEDIR=${DIR}/images-$(date +%b-%Y)
-
-URL=$1
-ZIP=$(basename ${URL})
-FOLDER=$(echo ${ZIP} | awk -F-factory '{print $1}')
-IMAGE=image-${FOLDER}.zip
-mkdir -p ${SAVEDIR}
-mkdir -p ${DIR}
-cd ${DIR}
-wget ${URL}
-unzip ${ZIP}
-cd ${FOLDER}
-unzip ${IMAGE}
-cp vendor.img ${SAVEDIR}/${DEVICE}-vendor-$(date +%b-%Y).img
-cp radio-${DEVICE}*.img ${SAVEDIR}/${DEVICE}-radio-$(date +%b-%Y).img
-cp bootloader-${DEVICE}*.img ${SAVEDIR}/${DEVICE}-bootloader-$(date +%b-%Y).img
-cp boot.img ${SAVEDIR}/${DEVICE}-boot-$(date +%b-%Y).img
-rm -rf ${DIR}/${ZIP}
-
-# Upload to gdrive
-if [[ ${GD_FOLDER} != "" ]]; then
-    rm -rf ${GD_IMAGES}/*
-    mkdir -p ${GD_IMAGES}
-    cp vendor.img ${GD_IMAGES}/${DEVICE}-vendor-$(date +%b-%Y).img
-    cp radio-${DEVICE}*.img ${GD_IMAGES}/${DEVICE}-radio-$(date +%b-%Y).img
-    cp bootloader-${DEVICE}*.img ${GD_IMAGES}/${DEVICE}-bootloader-$(date +%b-%Y).img
-    cp boot.img ${GD_IMAGES}/${DEVICE}-boot-$(date +%b-%Y).img
-    cd ${GD_FOLDER}
-    grive
-        dc_msg "**Google Drive: $(date +%B)'s vendor, radio, bootloader, and boot images have been uploaded! ${GD_IMAGESURL}**"
-    fi
+## Remove factory ZIP ##
+rm -rf ${FI_ZIP}
