merge-ls: check if merge failed && inform
Signed-off-by: shagbag913 <sh4gbag913@gmail.com>

diff --git a/merge-ls b/merge-ls
--- a/merge-ls
+++ b/merge-ls
@@ -24,4 +24,6 @@ if [[ v${VER} = ${LATEST_VER} ]]; then
 fi
 
 # Merge!
-git merge ${LATEST_VER}
+if ! git merge ${LATEST_VER}; then
+    error "Merge failed! Fix the conflicts!"
+fi
